name: go-game
channels:
- conda-forge
- defaults
- asmeurer
- snowflakedb
dependencies:
- agate=1.6.0=py36_2
- agate-dbf=0.2.0=py36_0
- agate-excel=0.2.1=py36_0
- agate-sql=0.5.2=py36_0
- asn1crypto=0.22.0=py36_0
- babel=2.4.0=py36_0
- ca-certificates=2017.7.27.1=0
- certifi=2017.7.27.1=py36_0
- cffi=1.10.0=py36_0
- chardet=3.0.4=py36_0
- click=6.7=py36_0
- coverage=4.4.1=py36_0
- cryptography=2.0.3=py36_0
- csvkit=1.0.2=py36_0
- dbfread=2.0.7=py36_0
- et_xmlfile=1.0.1=py36_0
- isodate=0.5.4=py36_0
- jdcal=1.3=py36_0
- leather=0.3.3=py36_0
- libffi=3.2.1=3
- mysql-connector-python=2.2.2=py36_0
- ncurses=5.9=10
- openpyxl=2.5.0a3=py36_0
- openssl=1.0.2l=0
- parsedatetime=2.4=py36_0
- pip=9.0.1=py36_0
- py=1.4.34=py36_0
- pycparser=2.18=py36_0
- pyopenssl=17.2.0=py36_0
- pysocks=1.6.7=py36_0
- pytest=3.2.2=py_0
- pytest-cov=2.5.1=py36_0
- python=3.6.2=0
- python-slugify=1.2.4=py36_1
- pytimeparse=1.1.7=py36_0
- pytz=2017.2=py36_0
- readline=6.2=0
- requests=2.18.4=py36_1
- requests-toolbelt=0.8.0=py36_0
- setuptools=36.3.0=py36_0
- six=1.10.0=py36_1
- sqlalchemy=1.1.13=py36_0
- sqlite=3.13.0=1
- tk=8.5.19=2
- unidecode=0.04.21=py36_0
- urllib3=1.22=py36_0
- wheel=0.29.0=py36_0
- xz=5.2.3=0
- zlib=1.2.11=0
- idna=2.6=py36_0
- pymysql=0.7.9=py36_0
- xlrd=1.1.0=py36_0
- pip:
  - boto3==1.4.6
  - botocore==1.6.8
  - docutils==0.14
  - et-xmlfile==1.0.1
  - future==0.16.0
  - hvac==0.2.17
  - ijson==2.3
  - jmespath==0.9.3
  - pyasn1==0.2.3
  - pyasn1-modules==0.0.9
  - pycryptodome==3.4.7
  - python-dateutil==2.6.1
  - s3transfer==0.1.11
  - snowflake-connector-python==1.4.6
  - snowflake-sqlalchemy==1.0.7

